// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koxzkipmnaaekqoehzxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtveHpraXBtbmFhZWtxb2Voenh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjA3MTMsImV4cCI6MjA2NDYzNjcxM30.7w9GJXhHYNGwF1dEZ5NQRE-pr5KAuiquwHd8BQcbCCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);